package edu.utdallas.mavs.divas.core.sim.common.stimulus;

import java.io.Serializable;

/**
 * This class describes an agent stimulus.
 * <p>
 * An agent stimulus is generated by an agent to influence its situated environment.
 */
public abstract class AgentStimulus implements Serializable
{
    private static final long serialVersionUID = 1L;

    /**
     * the agent's ID
     */
    protected int             id;

    /**
     * Creates a new agent stimulus.
     * 
     * @param id the agent's ID
     */
    protected AgentStimulus(int id)
    {
        this.id = id;
    }

    /**
     * Gets the ID of the agent
     * 
     * @return the agent's ID
     */
    public int getId()
    {
        return id;
    }

    /**
     * Sets the ID of the agent
     * 
     * @param id the agent's ID
     */
    public void setId(int id)
    {
        this.id = id;
    }
}
