package edu.utdallas.mavs.divas.core.sim.agent.planning;

import edu.utdallas.mavs.divas.core.sim.agent.knowledge.KnowledgeModule;
import edu.utdallas.mavs.divas.core.sim.agent.task.TaskModule;
import edu.utdallas.mavs.divas.core.sim.common.stimulus.Stimuli;

/**
 * An agent's plan executor module
 * 
 * @param <KM>
 *        The agent's knowledge module.
 * @param <TM>
 *        The agent's task module
 */
public interface PlanExecutor<KM extends KnowledgeModule<?>, TM extends TaskModule<KM>>
{
    /**
     * Execute the best plan selected by the plan selector.
     * @param plan TODO
     * 
     * @return the stimuli generated by the plan to be executed.
     */
    public Stimuli executePlan(Plan plan);
}
